[technote]
id = "RTN-100"
series_id = "RTN"
canonical_url = "https://rtn-100.lsst.io"
github_url = "https://github.com/lsst/rtn-100"
github_default_branch = "main"
date_created = 2025-06-12T16:27:04Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Jennifer K."
name.family = "Adelman-McCarthy"
internal_id = "adelmanmccarthyj"
orcid = "https://orcid.org/0000-0002-4100-8928"
[[technote.authors.affiliations]]
name = "Fermi National Accelerator Laboratory"
internal_id = "Fermilab"
address = "P. O. Box 500, Batavia, IL 60510, USA"
