[technote]
id = "RTN-100"
series_id = "RTN"
canonical_url = "https://rtn-100.lsst.io"
github_url = "https://github.com/lsst/rtn-100"
github_default_branch = "main"
date_created = 2025-06-12T16:27:04Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

#[technote.status]
#state = "draft"

[[technote.authors]]
name.given = "Jennifer K."
name.family = "Adelman-McCarthy"
internal_id = "adelmanmccarthyj"
orcid = "https://orcid.org/0000-0002-4100-8928"
[[technote.authors.affiliations]]
name = "Fermi National Accelerator Laboratory"
internal_id = "Fermilab"
address = "P. O. Box 500, Batavia, IL 60510, USA"
[[technote.authors]]
name.given = "Brian"
name.family = "Yanny"
[[technote.authors]]
name.given = "Steve"
name.family = "Pietrowicz"
[[technote.authors]]
name.given = "Fabio"
name.family = "Hernandez"
[[technote.authors]]
name.given = "Peter"
name.family = "Love"
[[technote.authors]]
name.given = "Tim"
name.family = "Noble"
[[technote.authors]]
name.given = "Quentin"
name.family = "Le Boulc'h"
[[technote.authors]]
name.given = "Dave"
name.family = "McKay"
[[technote.authors]]
name.given = "Matthew"
name.family = "Sims"
[[technote.authors]]
name.given = "George"
name.family = "Beckett"
[[technote.authors]]
name.given = "Michelle"
name.family = "Gower"
[[technote.authors]]
name.given = "Greg"
name.family = "Daues"
[[technote.authors]]
name.given = "Hsin-Fang"
name.family = "Chiang"
[[technote.authors]]
name.given = "Jhonatan"
name.family = "Amado"
[[technote.authors]]
name.given = "Jim"
name.family = "Chiang"
[[technote.authors]]
name.given = "K T"
name.family = "Lim"
[[technote.authors]]
name.given = "Matt"
name.family = "Doidge"
[[technote.authors]]
name.given = "Steven"
name.family = "Simpson"
[[technote.authors]]
name.given = "Tim"
name.family = "Jenness"
[[technote.authors]]
name.given = "Wen"
name.family = "Guan"
[[technote.authors]]
name.given = "Zhaoyu"
name.family = "Yang"
[[technote.authors]]
name.given = "Jim"
name.family = "Bosch"
[[technote.authors]]
name.given = "Yusra"
name.family = "AlSayyad"
